name: Deploy VS Code Extension

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i

      - name: Install vsce
        run: npm install -g vsce

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV  # Guardar la versión como una variable de entorno

      - name: Package extension
        run: vsce package --out ismola-extension-pack-${{ env.VERSION }}.vsix  # Usa la versión dinámica en el nombre del archivo

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VSCE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ./ismola-extension-pack-${{ env.VERSION }}.vsix  # Usa la misma versión aquí